[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "3ZymoFt5iejQYVLnxvpU4pd3ekexHXkcrBiypRvqarU3"

[programs.devnet]
voting = "3ZymoFt5iejQYVLnxvpU4pd3ekexHXkcrBiypRvqarU3"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
